import { StyleSheet, Platform } from 'react-native';
import { TYPOGRAPHY } from '../../constants';

const createStyles = themeColor =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: themeColor || '#5C7E9D', // StackMap blue background
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: themeColor || '#5C7E9D',
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: '#ffffff',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: themeColor || '#5C7E9D',
      padding: 32,
    },
    errorTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#ffffff',
      marginTop: 16,
      marginBottom: 8,
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Bold',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    errorMessage: {
      fontSize: 16,
      color: '#ffffff',
      textAlign: 'center',
      opacity: 0.9,
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    backButton: {
      marginTop: 24,
      paddingHorizontal: 24,
      paddingVertical: 12,
      backgroundColor: '#ffffff',
      borderRadius: 8,
    },
    backButtonText: {
      color: themeColor || '#5C7E9D',
      fontSize: 16,
      fontWeight: '600',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    header: {
      backgroundColor: themeColor || '#5C7E9D',
      paddingHorizontal: 16,
      paddingVertical: 20,
      borderBottomWidth: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      ...Platform.select({
        web: {
          paddingHorizontal: 24,
        },
      }),
    },
    userInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    userTextContainer: {
      flex: 1,
    },
    headerControls: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    userIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#ffffff',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    userIcon: {
      fontSize: 24,
      color: themeColor || '#5C7E9D',
      fontFamily: TYPOGRAPHY.fontFamily.regular,
    },
    userImage: {
      width: 40,
      height: 40,
    },
    userName: {
      fontSize: 18,
      fontWeight: '700',
      color: '#ffffff',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Bold',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    shareInfo: {
      fontSize: 12,
      color: 'rgba(255, 255, 255, 0.8)',
      marginTop: 2,
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    recipientInfo: {
      fontSize: 12,
      color: 'rgba(255, 255, 255, 0.8)',
      fontStyle: 'italic',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    ctaButton: {
      backgroundColor: '#ffffff',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: themeColor || '#5C7E9D',
    },
    ctaButtonImage: {
      width: 20,
      height: 20,
      marginRight: 8,
    },
    ctaButtonText: {
      color: themeColor || '#5C7E9D',
      fontSize: 14,
      fontWeight: '600',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    noteContainer: {
      backgroundColor: '#fff9e6',
      borderLeftWidth: 4,
      borderLeftColor: '#ffb300',
      paddingHorizontal: 16,
      paddingVertical: 12,
      margin: 16,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    noteText: {
      flex: 1,
      marginLeft: 8,
      fontSize: 14,
      color: '#5d4e37',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    progressInfo: {
      fontSize: 14,
      color: '#ffffff',
      marginTop: 4,
      fontWeight: '600',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Bold',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    daySelector: {
      flexDirection: 'row',
      backgroundColor: '#ffffff',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(92, 126, 157, 0.1)',
    },
    dayTab: {
      paddingHorizontal: 20,
      paddingVertical: 8,
      marginRight: 12,
      borderRadius: 20,
      backgroundColor: 'rgba(92, 126, 157, 0.1)',
    },
    dayTabActive: {
      backgroundColor: themeColor || '#5C7E9D',
    },
    dayTabText: {
      fontSize: 14,
      color: '#666666',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    dayTabTextActive: {
      color: '#ffffff',
      fontWeight: '600',
    },
    progressSummary: {
      backgroundColor: '#ffffff',
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 16,
      marginHorizontal: 16,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    progressText: {
      fontSize: 14,
      color: '#666666',
      marginBottom: 8,
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    progressBar: {
      height: 8,
      backgroundColor: 'rgba(92, 126, 157, 0.2)',
      borderRadius: 4,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 4,
    },
    activitiesContainer: {
      flex: 1,
      paddingHorizontal: 16,
    },
    activityCard: {
      backgroundColor: '#ffffff',
      borderRadius: 12,
      padding: 16,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    activityContent: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    activityEmojiContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: themeColor || '#5C7E9D',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    activityEmoji: {
      fontSize: 20,
      color: '#ffffff',
      fontFamily: TYPOGRAPHY.fontFamily.regular,
    },
    activityImage: {
      width: 30,
      height: 30,
    },
    activityTextContainer: {
      flex: 1,
    },
    activityTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#000000',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Bold',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    activityCategory: {
      fontSize: 12,
      color: '#666666',
      marginTop: 2,
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    completedBadge: {
      backgroundColor: '#4caf50',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
    },
    completedText: {
      fontSize: 10,
      color: '#ffffff',
      fontWeight: '600',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
    },
    emptyMessage: {
      fontSize: 16,
      color: '#ffffff',
      textAlign: 'center',
      marginTop: 16,
      opacity: 0.9,
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    footerInfo: {
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      padding: 16,
      margin: 16,
      borderRadius: 12,
      alignItems: 'center',
    },
    footerText: {
      fontSize: 12,
      color: '#666666',
      textAlign: 'center',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Regular',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
    mobileCtaContainer: {
      position: 'absolute',
      bottom: 20,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 10,
    },
    mobileCtaButton: {
      backgroundColor: '#ffffff',
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: themeColor || '#5C7E9D',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    mobileCtaButtonImage: {
      width: 24,
      height: 24,
      marginRight: 8,
    },
    mobileCtaButtonText: {
      color: themeColor || '#5C7E9D',
      fontSize: 16,
      fontWeight: '700',
      fontFamily: Platform.select({
        ios: 'Comic Relief',
        android: 'ComicRelief-Bold',
        web: "'Comic Relief', 'Comic Sans MS', cursive",
      }),
    },
  });

export default createStyles;