import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, TYPOGRAPHY, SPACING, RADIUS } from '../../../constants';

const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  scrollContent: {
    flexGrow: 1,
  },
  safeArea: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    padding: SPACING.lg,
  },
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 20,
    left: 20,
    zIndex: 10,
    padding: 10,
  },
  stepContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: screenWidth >= 768 ? 600 : '100%',
    alignSelf: 'center',
    width: '100%',
  },
  title: {
    fontSize: screenWidth >= 768 ? 32 : 28,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontWeight: 'bold',
    color: '#000',
    marginTop: SPACING.lg,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: screenWidth >= 768 ? 18 : 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    marginBottom: SPACING.xl,
    textAlign: 'center',
  },
  optionsContainer: {
    width: '100%',
    marginTop: SPACING.lg,
  },
  primaryButton: {
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    borderRadius: RADIUS.lg,
    marginBottom: SPACING.md,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontWeight: '600',
  },
  secondaryButton: {
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    borderRadius: RADIUS.lg,
    borderWidth: 2,
    borderColor: '#5C7E9D',
    marginBottom: SPACING.md,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontWeight: '600',
  },
  skipButton: {
    padding: SPACING.md,
    alignItems: 'center',
  },
  skipButtonText: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  optionCard: {
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    borderWidth: 2,
    marginBottom: SPACING.md,
    alignItems: 'center',
  },
  optionTitle: {
    fontSize: 18,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontWeight: '600',
    color: '#000',
    marginTop: SPACING.sm,
  },
  optionDescription: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  inputGroup: {
    width: '100%',
    marginBottom: SPACING.lg,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    marginBottom: SPACING.md,
  },
  emojiSelector: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: SPACING.md,
  },
  emojiOption: {
    padding: SPACING.sm,
    borderRadius: RADIUS.md,
  },
  emojiText: {
    fontSize: 30,
  },
  usersList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: SPACING.lg,
  },
  userPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.gray[200],
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.round,
    margin: SPACING.xs,
  },
  userPillEmoji: {
    fontSize: 20,
    marginRight: SPACING.xs,
  },
  userPillName: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#000',
  },
  errorText: {
    color: '#ff4444',
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    marginTop: SPACING.sm,
    textAlign: 'center',
  },
  charCount: {
    fontSize: 12,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    textAlign: 'right',
  },
  syncCodeContainer: {
    backgroundColor: COLORS.gray[100],
    padding: SPACING.lg,
    borderRadius: RADIUS.lg,
    marginVertical: SPACING.lg,
    width: '100%',
  },
  syncCode: {
    fontSize: 18,
    fontFamily: 'monospace',
    color: '#000',
    textAlign: 'center',
    marginBottom: SPACING.md,
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
  },
  copyButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    marginLeft: SPACING.xs,
  },
  syncCodeHint: {
    fontSize: 12,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    textAlign: 'center',
    marginTop: SPACING.xs,
  },
  processingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.xl,
    minHeight: 120,
  },
  processingText: {
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#333',
    marginTop: SPACING.sm,
    textAlign: 'center',
  },
  processingSubtext: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  toast: {
    position: 'absolute',
    bottom: 100,
    backgroundColor: COLORS.opacity.blackOverlay80,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.md,
  },
  toastText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  warningText: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#ff9800',
    textAlign: 'center',
    marginBottom: SPACING.lg,
  },
  previewContainer: {
    backgroundColor: COLORS.gray[100],
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.lg,
    width: '100%',
  },
  previewTitle: {
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontWeight: '600',
    color: '#000',
    marginBottom: SPACING.sm,
  },
  previewText: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    marginBottom: SPACING.xs,
  },
  successInfo: {
    backgroundColor: COLORS.ui.bgGreenTint,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    marginVertical: SPACING.lg,
    width: '100%',
  },
  infoText: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#2e7d32',
    textAlign: 'center',
  },
  summaryContainer: {
    backgroundColor: COLORS.gray[100],
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    marginVertical: SPACING.lg,
    width: '100%',
  },
  summaryTitle: {
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontWeight: '600',
    color: '#000',
    marginBottom: SPACING.sm,
  },
  summaryText: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    marginBottom: SPACING.xs,
  },
  logoSection: {
    alignItems: 'center',
    marginBottom: SPACING.xl,
  },
  logoText: {
    fontSize: screenWidth >= 768 ? 36 : 32,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontWeight: 'bold',
    color: '#000',
    marginTop: SPACING.md,
  },
  tagline: {
    fontSize: screenWidth >= 768 ? 16 : 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: '#666',
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  footerLinks: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.xl,
    paddingVertical: SPACING.md,
  },
  footerLink: {
    padding: SPACING.sm,
  },
  footerLinkText: {
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    textDecorationLine: 'underline',
  },
  footerSeparator: {
    fontSize: 14,
    color: '#666',
    marginHorizontal: SPACING.sm,
  },
  versionContainer: {
    marginTop: SPACING.md,
    alignItems: 'center',
  },
  versionText: {
    fontSize: 12,
    color: '#999',
    fontFamily: 'Comic Relief',
  },
});