import React, { useState, useEffect } from 'react';
import { Text, TextInput } from '../Typography';
import {
  View,
  TouchableOpacity,
  Modal,
  ScrollView,
  StyleSheet,
  Image,
  FlatList,
  SafeAreaView,
  Dimensions,
  Platform,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';
import {
  SHADOWS,
  TYPOGRAPHY,
  SPACING,
  RADIUS,
  COLORS,
  isTablet,
  CUSTOM_IMAGE_SOURCES,
  getCustomImageSource,
} from '../../constants';
import emojiData from 'emoji-datasource-apple/emoji.json';
import EmojiSearch, { performEmojiSearch } from './EmojiSearch';
import SearchResults from './SearchResults';
import { applySkinTone, supportsSkinTone, SKIN_TONE_MODIFIERS } from './skinToneUtils';

const { width: screenWidth } = Dimensions.get('window');

// Create emoji search index from emoji data
const createEmojiSearchIndex = () => {
  const searchIndex = {};
  emojiData.forEach(emoji => {
    if (emoji.unified) {
      // Convert unified code to actual emoji
      const emojiChar = String.fromCodePoint(
        ...emoji.unified.split('-').map(u => parseInt(u, 16)),
      );

      // Index by short names, keywords, and category
      const searchTerms = [
        ...(emoji.short_names || []),
        ...(emoji.keywords || []),
        emoji.category,
      ];

      searchIndex[emojiChar] = {
        emoji: emojiChar,
        searchTerms: searchTerms.map(term => term.toLowerCase()),
        category: emoji.category,
        sortOrder: emoji.sort_order,
      };
    }
  });
  return searchIndex;
};

const EMOJI_SEARCH_INDEX = createEmojiSearchIndex();

// Simple emoji categories for now - we'll use the comprehensive search
const EMOJI_CATEGORIES = {
  Smileys: [
    '😀',
    '😃',
    '😄',
    '😁',
    '😅',
    '😂',
    '🤣',
    '😊',
    '😇',
    '🙂',
    '😉',
    '😌',
    '😍',
    '🥰',
    '😘',
    '😗',
    '😙',
    '😚',
    '😋',
    '😛',
    '😝',
    '😜',
    '🤪',
    '🤨',
    '🧐',
    '🤓',
    '😎',
    '🤩',
    '🥳',
    '😏',
    '😒',
    '😞',
    '😔',
    '😟',
    '😕',
    '🙁',
    '☹️',
    '😣',
    '😖',
    '😫',
    '😩',
    '🥺',
    '😢',
    '😭',
    '😤',
    '😠',
    '😡',
    '🤬',
    '🤯',
    '😳',
    '🥵',
    '🥶',
    '😱',
    '😨',
    '😰',
    '😥',
    '😓',
    '🤗',
    '🤔',
    '🤭',
    '🤫',
    '🤥',
    '😶',
    '😐',
    '😑',
    '😬',
    '🙄',
    '😯',
    '😦',
    '😧',
    '😮',
    '😲',
    '🥱',
    '😴',
    '🤤',
    '😪',
    '😵',
    '🤐',
    '🥴',
    '🤢',
    '🤮',
    '🤧',
    '😷',
    '🤒',
    '🤕',
  ],
  People: [
    '👶',
    '👧',
    '🧒',
    '👦',
    '👩',
    '🧑',
    '👨',
    '👩‍🦱',
    '🧑‍🦱',
    '👨‍🦱',
    '👩‍🦰',
    '🧑‍🦰',
    '👨‍🦰',
    '👱‍♀️',
    '👱',
    '👱‍♂️',
    '👩‍🦳',
    '🧑‍🦳',
    '👨‍🦳',
    '👩‍🦲',
    '🧑‍🦲',
    '👨‍🦲',
    '🧔‍♀️',
    '🧔',
    '🧔‍♂️',
    '👵',
    '🧓',
    '👴',
    '👲',
    '👳‍♀️',
    '👳',
    '👳‍♂️',
    '🧕',
    '👮‍♀️',
    '👮',
    '👮‍♂️',
    '👷‍♀️',
    '👷',
    '👷‍♂️',
    '💂‍♀️',
    '💂',
    '💂‍♂️',
    '🕵️‍♀️',
    '🕵️',
    '🕵️‍♂️',
    '👩‍⚕️',
    '🧑‍⚕️',
    '👨‍⚕️',
    '👩‍🌾',
    '🧑‍🌾',
    '👨‍🌾',
    '👩‍🍳',
    '🧑‍🍳',
    '👨‍🍳',
    '👩‍🎓',
    '🧑‍🎓',
    '👨‍🎓',
    '👩‍🎤',
    '🧑‍🎤',
    '👨‍🎤',
    '👩‍🏫',
    '🧑‍🏫',
    '👨‍🏫',
    '👩‍🏭',
    '🧑‍🏭',
    '👨‍🏭',
    '👩‍💻',
    '🧑‍💻',
    '👨‍💻',
    '👩‍💼',
    '🧑‍💼',
    '👨‍💼',
    '👩‍🔧',
    '🧑‍🔧',
    '👨‍🔧',
    '👩‍🔬',
    '🧑‍🔬',
    '👨‍🔬',
    '👩‍🎨',
    '🧑‍🎨',
    '👨‍🎨',
    '👩‍🚒',
    '🧑‍🚒',
    '👨‍🚒',
    '👩‍✈️',
    '🧑‍✈️',
    '👨‍✈️',
    '👩‍🚀',
    '🧑‍🚀',
    '👨‍🚀',
    '👩‍⚖️',
    '🧑‍⚖️',
    '👨‍⚖️',
    '👰‍♀️',
    '👰',
    '👰‍♂️',
    '🤵‍♀️',
    '🤵',
    '🤵‍♂️',
    '👸',
    '🤴',
    '🥷',
    '🦸‍♀️',
    '🦸',
    '🦸‍♂️',
    '🦹‍♀️',
    '🦹',
    '🦹‍♂️',
    '🤶',
    '🧑‍🎄',
    '🎅',
    '🧙‍♀️',
    '🧙',
    '🧙‍♂️',
    '🧝‍♀️',
    '🧝',
    '🧝‍♂️',
    '🧛‍♀️',
    '🧛',
    '🧛‍♂️',
    '🧟‍♀️',
    '🧟',
    '🧟‍♂️',
    '🧞‍♀️',
    '🧞',
    '🧞‍♂️',
    '🧜‍♀️',
    '🧜',
    '🧜‍♂️',
    '🧚‍♀️',
    '🧚',
    '🧚‍♂️',
    '👼',
    '🤰',
    '🤱',
    '👩‍🍼',
    '🧑‍🍼',
    '👨‍🍼',
    '🙇‍♀️',
    '🙇',
    '🙇‍♂️',
    '💁‍♀️',
    '💁',
    '💁‍♂️',
    '🙅‍♀️',
    '🙅',
    '🙅‍♂️',
    '🙆‍♀️',
    '🙆',
    '🙆‍♂️',
    '🙋‍♀️',
    '🙋',
    '🙋‍♂️',
    '🧏‍♀️',
    '🧏',
    '🧏‍♂️',
    '🤦‍♀️',
    '🤦',
    '🤦‍♂️',
    '🤷‍♀️',
    '🤷',
    '🤷‍♂️',
    '🙎‍♀️',
    '🙎',
    '🙎‍♂️',
    '🙍‍♀️',
    '🙍',
    '🙍‍♂️',
    '💇‍♀️',
    '💇',
    '💇‍♂️',
    '💆‍♀️',
    '💆',
    '💆‍♂️',
    '🧖‍♀️',
    '🧖',
    '🧖‍♂️',
    '💅',
    '🤳',
    '💃',
    '🕺',
    '👯‍♀️',
    '👯',
    '👯‍♂️',
    '🕴️',
    '👩‍🦽',
    '🧑‍🦽',
    '👨‍🦽',
    '👩‍🦼',
    '🧑‍🦼',
    '👨‍🦼',
    '🚶‍♀️',
    '🚶',
    '🚶‍♂️',
    '👩‍🦯',
    '🧑‍🦯',
    '👨‍🦯',
    '🧎‍♀️',
    '🧎',
    '🧎‍♂️',
    '🏃‍♀️',
    '🏃',
    '🏃‍♂️',
    '🧍‍♀️',
    '🧍',
    '🧍‍♂️',
    '👫',
    '👭',
    '👬',
    '👩‍❤️‍👨',
    '👩‍❤️‍👩',
    '💑',
    '👨‍❤️‍👨',
    '👩‍❤️‍💋‍👨',
    '👩‍❤️‍💋‍👩',
    '💏',
    '👨‍❤️‍💋‍👨',
    '👨‍👩‍👦',
    '👨‍👩‍👧',
    '👨‍👩‍👧‍👦',
    '👨‍👩‍👦‍👦',
    '👨‍👩‍👧‍👧',
    '👩‍👩‍👦',
    '👩‍👩‍👧',
    '👩‍👩‍👧‍👦',
    '👩‍👩‍👦‍👦',
    '👩‍👩‍👧‍👧',
    '👨‍👨‍👦',
    '👨‍👨‍👧',
    '👨‍👨‍👧‍👦',
    '👨‍👨‍👦‍👦',
    '👨‍👨‍👧‍👧',
    '👩‍👦',
    '👩‍👧',
    '👩‍👧‍👦',
    '👩‍👦‍👦',
    '👩‍👧‍👧',
    '👨‍👦',
    '👨‍👧',
    '👨‍👧‍👦',
    '👨‍👦‍👦',
    '👨‍👧‍👧',
    '🤲',
    '👐',
    '🙌',
    '👏',
    '🤝',
    '👍',
    '👎',
    '👊',
    '✊',
    '🤛',
    '🤜',
    '🤞',
    '✌️',
    '🤟',
    '🤘',
    '👌',
    '🤌',
    '🤏',
    '👈',
    '👉',
    '👆',
    '👇',
    '☝️',
    '✋',
    '🤚',
    '🖐️',
    '🖖',
    '👋',
    '🤙',
    '💪',
    '🦾',
    '🖕',
    '✍️',
    '🙏',
    '🦶',
    '🦵',
    '🦿',
    '💄',
    '💋',
    '👄',
    '🦷',
    '👅',
    '👂',
    '🦻',
    '👃',
    '👣',
    '👁️',
    '👀',
    '🫀',
    '🫁',
    '🧠',
    '🦴',
    '🦳',
    '🦱',
    '🦲',
    '🦰',
  ],
  Lifestyle: [
    '👕',
    '👔',
    '👗',
    '👘',
    '👙',
    '👚',
    '👛',
    '👜',
    '👝',
    '🎒',
    '👞',
    '👟',
    '🥾',
    '🥿',
    '👠',
    '👡',
    '👢',
    '👑',
    '👒',
    '🎩',
    '🎓',
    '🧢',
    '⛑️',
    '🪖',
    '💄',
    '💍',
    '💼',
    '🧳',
    '👓',
    '🕶️',
    '🥽',
    '🌂',
    '🧥',
    '🦺',
    '👖',
    '🧣',
    '🧤',
    '🧦',
    '🪥',
    '🧼',
    '🧽',
    '🧴',
    '🛁',
    '🚿',
    '🚽',
    '🧻',
    '🪒',
    '💊',
    '💉',
    '🩹',
    '🩺',
    '🌡️',
    '🧹',
    '🧺',
    '🧯',
    '🛏️',
    '🛋️',
    '🪑',
    '🚪',
    '🪟',
    '🧱',
    '🏠',
    '🏡',
    '🏘️',
    '🍳',
    '🥘',
    '🍲',
    '🥗',
    '🍱',
    '🍜',
    '🍝',
    '🍕',
    '🍔',
    '🥪',
    '🌮',
    '🌯',
    '🥙',
    '🍖',
    '🍗',
    '🥩',
    '🥓',
    '🧀',
    '🥚',
    '🥞',
    '🧇',
    '🥐',
    '🍞',
    '🥖',
    '🥨',
    '🍩',
    '🍪',
    '🎂',
    '🍰',
    '🧁',
    '🍫',
    '🍬',
    '🍭',
    '🍯',
    '🥛',
    '☕',
    '🍵',
    '🧃',
    '🥤',
    '🧊',
    '🍽️',
    '🍴',
    '🥄',
    '🔪',
    '🧭',
    '🧷',
    '🧵',
    '🪡',
    '🧶',
    '🪢',
    '🧲',
    '🔑',
    '🗝️',
    '🪜',
    '🧰',
    '🪛',
    '🔧',
    '🔨',
    '⚒️',
    '🪚',
    '🔩',
    '⚙️',
    '🪙',
    '💳',
    '💰',
    '💵',
    '💸',
    '🧾',
    '✉️',
    '📧',
    '📨',
    '📬',
    '📮',
    '🗳️',
    '✏️',
    '✒️',
    '🖊️',
    '🖌️',
    '📝',
    '📄',
    '📃',
    '📑',
    '📊',
    '📈',
    '📉',
    '📆',
    '📅',
    '🗓️',
    '📇',
    '🗂️',
    '📁',
    '🗄️',
    '🗑️',
    '📱',
    '☎️',
    '📞',
    '📟',
    '📠',
    '💻',
    '🖥️',
    '⌨️',
    '🖱️',
    '🖨️',
    '🗜️',
    '💽',
    '💾',
    '💿',
    '📀',
    '🎥',
    '📹',
    '📷',
    '📸',
    '🔦',
    '💡',
    '🕯️',
    '🪔',
    '🔌',
    '🔋',
    '🪫',
    '🚰',
    '🚬',
    '⚰️',
    '🪦',
    '⚱️',
    '🗿',
    '🪧',
    '🏧',
    '🚮',
    '🚻',
    '🚹',
    '🚺',
    '🚼',
    '🚾',
    '🛂',
    '🛃',
    '🛄',
    '🛅',
  ],
  Food: [
    '🍏',
    '🍎',
    '🍐',
    '🍊',
    '🍋',
    '🍌',
    '🍉',
    '🍇',
    '🍓',
    '🍈',
    '🍒',
    '🍑',
    '🥭',
    '🍍',
    '🥥',
    '🥝',
    '🍅',
    '🍆',
    '🥑',
    '🥦',
    '🥬',
    '🥒',
    '🌶️',
    '🌽',
    '🥕',
    '🥔',
    '🍠',
    '🥐',
    '🥖',
    '🍞',
    '🥨',
    '🧀',
    '🥚',
    '🍳',
    '🥞',
    '🥓',
    '🥩',
    '🍗',
    '🍖',
    '🌭',
    '🍔',
    '🍟',
    '🍕',
    '🥪',
    '🥙',
    '🌮',
    '🌯',
    '🥗',
    '🥘',
    '🥫',
    '🍝',
    '🍜',
    '🍲',
    '🍛',
    '🍣',
    '🍱',
    '🍤',
    '🍙',
    '🍚',
    '🍘',
    '🍥',
    '🥮',
    '🍢',
    '🍡',
    '🍧',
    '🍨',
    '🍦',
    '🥧',
    '🧁',
    '🍰',
    '🎂',
    '🍮',
    '🍭',
    '🍬',
    '🍫',
    '🍿',
    '🍩',
    '🍪',
    '🌰',
    '🥜',
    '🍯',
    '🥛',
    '🍼',
    '☕',
    '🍵',
    '🥤',
    '🍶',
    '🍺',
    '🍻',
    '🥂',
    '🍷',
    '🥃',
    '🍸',
    '🍹',
    '🍾',
  ],
  Animals: [
    '🐶',
    '🐱',
    '🐭',
    '🐹',
    '🐰',
    '🦊',
    '🐻',
    '🐼',
    '🐨',
    '🐯',
    '🦁',
    '🐮',
    '🐷',
    '🐽',
    '🐸',
    '🐵',
    '🙈',
    '🙉',
    '🙊',
    '🐒',
    '🐔',
    '🐧',
    '🐦',
    '🐤',
    '🐣',
    '🐥',
    '🦆',
    '🦅',
    '🦉',
    '🦇',
    '🐺',
    '🐗',
    '🐴',
    '🦄',
    '🐝',
    '🐛',
    '🦋',
    '🐌',
    '🐞',
    '🐜',
    '🦟',
    '🦗',
    '🕷️',
    '🕸️',
    '🦂',
    '🐢',
    '🐍',
    '🦎',
    '🦖',
    '🦕',
    '🐙',
    '🦑',
    '🦐',
    '🦀',
    '🐡',
    '🐠',
    '🐟',
    '🐬',
    '🐳',
    '🐋',
    '🦈',
    '🐊',
    '🐅',
    '🐆',
    '🦓',
    '🦍',
    '🦧',
    '🐘',
    '🦛',
    '🦏',
    '🐪',
    '🐫',
    '🦒',
    '🦘',
    '🐃',
    '🐂',
    '🐄',
    '🐎',
    '🐖',
    '🐏',
    '🐑',
    '🦙',
    '🐐',
    '🦌',
    '🐕',
    '🐩',
    '🦮',
    '🐕‍🦺',
    '🐈',
    '🐈‍⬛',
    '🐓',
    '🦃',
    '🦚',
    '🦜',
    '🦢',
    '🦩',
    '🕊️',
    '🐇',
    '🦝',
    '🦨',
    '🦡',
    '🦦',
    '🦥',
    '🐁',
    '🐀',
    '🐿️',
    '🦔',
  ],
  Travel: [
    '🚗',
    '🚕',
    '🚙',
    '🚌',
    '🚎',
    '🏎️',
    '🚓',
    '🚑',
    '🚒',
    '🚐',
    '🛻',
    '🚚',
    '🚛',
    '🚜',
    '🏍️',
    '🛵',
    '🚲',
    '🛴',
    '🚁',
    '🛸',
    '🚀',
    '✈️',
    '🛫',
    '🛬',
    '🪂',
    '💺',
    '🚤',
    '⛵',
    '🛶',
    '🚢',
    '🛳️',
    '⚓',
    '🚇',
    '🚊',
    '🚝',
    '🚄',
    '🚅',
    '🚈',
    '🚂',
    '🚆',
    '🚋',
    '🚃',
    '🚟',
    '🚠',
    '🚡',
    '🚖',
    '🚘',
    '🚍',
    '🚔',
    '🚨',
    '🚥',
    '🚦',
    '🛑',
    '🚧',
    '🏗️',
    '🏭',
    '🏠',
    '🏡',
    '🏘️',
    '🏚️',
    '🏢',
    '🏬',
    '🏣',
    '🏤',
    '🏥',
    '🏦',
    '🏨',
    '🏪',
    '🏫',
    '🏩',
    '💒',
    '🏛️',
    '⛪',
    '🕌',
    '🕍',
    '🛕',
    '🕋',
    '⛩️',
    '🗾',
    '🎑',
    '🏞️',
    '🌅',
    '🌄',
    '🌠',
    '🎇',
    '🎆',
    '🌇',
    '🌆',
    '🏙️',
    '🌃',
    '🌌',
    '🌉',
    '🌁',
  ],
  Objects: [
    '⌚',
    '📱',
    '📲',
    '💻',
    '⌨️',
    '🖥️',
    '🖨️',
    '🖱️',
    '🖲️',
    '🕹️',
    '🗜️',
    '💽',
    '💾',
    '💿',
    '📀',
    '📼',
    '📷',
    '📸',
    '📹',
    '🎥',
    '📽️',
    '🎞️',
    '📞',
    '☎️',
    '📟',
    '📠',
    '📺',
    '📻',
    '🎙️',
    '🎚️',
    '🎛️',
    '🧭',
    '⏱️',
    '⏲️',
    '⏰',
    '🕰️',
    '⌛',
    '⏳',
    '📡',
    '🔋',
    '🔌',
    '💡',
    '🔦',
    '🕯️',
    '🧯',
    '🛢️',
    '💸',
    '💵',
    '💴',
    '💶',
    '💷',
    '💰',
    '💳',
    '💎',
    '⚖️',
    '🧰',
    '🔧',
    '🔨',
    '⚒️',
    '🛠️',
    '⛏️',
    '🔩',
    '⚙️',
    '🧱',
    '⛓️',
    '🧲',
    '🔫',
    '💣',
    '🧨',
    '🔪',
    '🗡️',
    '⚔️',
    '🛡️',
    '🚬',
    '⚰️',
    '⚱️',
    '🏺',
    '🔮',
    '📿',
    '🧿',
    '💈',
    '⚗️',
    '🔭',
    '🔬',
    '🕳️',
    '💊',
    '💉',
    '🧬',
    '🦠',
    '🧫',
    '🧪',
    '🌡️',
    '🧹',
    '🧺',
    '🧻',
    '🚽',
    '🚰',
    '🚿',
    '🛁',
    '🛀',
    '🧼',
    '🧽',
    '🧴',
    '🛎️',
    '🔑',
    '🗝️',
    '🚪',
    '🛋️',
    '🛏️',
    '🛌',
    '🧸',
    '🖼️',
    '🛍️',
    '🛒',
    '🎁',
    '🎈',
    '🎏',
    '🎀',
    '🎊',
    '🎉',
    '🎎',
    '🏮',
    '🎐',
    '🧧',
    '✉️',
    '📩',
    '📨',
    '📧',
    '💌',
    '📥',
    '📤',
    '📦',
    '🏷️',
    '📪',
    '📫',
    '📬',
    '📭',
    '📮',
    '📯',
    '📜',
    '📃',
    '📄',
    '📑',
    '🧾',
    '📊',
    '📈',
    '📉',
    '🗒️',
    '🗓️',
    '📆',
    '📅',
    '🗑️',
    '📇',
    '🗃️',
    '🗳️',
    '🗄️',
    '📋',
    '📁',
    '📂',
    '🗂️',
    '🗞️',
    '📰',
    '📓',
    '📔',
    '📒',
    '📕',
    '📗',
    '📘',
    '📙',
    '📚',
    '📖',
    '🔖',
    '🧷',
    '🔗',
    '📎',
    '🖇️',
    '📐',
    '📏',
    '🧮',
    '📌',
    '📍',
    '✂️',
    '🖊️',
    '🖋️',
    '✒️',
    '🖌️',
    '🖍️',
    '📝',
    '✏️',
    '🔍',
    '🔎',
    '🔏',
    '🔐',
    '🔒',
    '🔓',
  ],
};

// Custom images list (matching PWA)
const CUSTOM_IMAGES = [
  { name: 'Chicken Nuggets', src: 'ChickenNuggets.png' },
  { name: 'Fish Sticks', src: 'FishSticks.png' },
  { name: 'Fusion', src: 'Fusion.png' },
  { name: 'Golden Retriever', src: 'GoldenRetriever.png' },
  { name: 'Goldfish Crackers', src: 'GoldfishCrackers.png' },
  { name: 'Kart', src: 'kart.png' },
  { name: 'Lambo', src: 'lambo.png' },
  { name: 'RAV4', src: 'RAV4.png' },
  { name: 'Swingset', src: 'Swingset.png' },
  { name: 'Breakfast Dog', src: 'breakfast_dog.png' },
];

const EmojiPicker = ({
  visible = false,
  onClose,
  onSelect,
  mode = 'modal', // 'modal' or 'inline'
  theme,
  selectedEmoji,
  showCustomImages = true,
}) => {
  const [selectedCategory, setSelectedCategory] = useState('Lifestyle');
  const [searchQuery, setSearchQuery] = useState('');
  const [filteredItems, setFilteredItems] = useState([]);
  const [categoryKeys, setCategoryKeys] = useState(
    Object.keys(EMOJI_CATEGORIES),
  );
  const [selectedSkinTone, setSelectedSkinTone] = useState(null);
  const [showSkinToneSelector, setShowSkinToneSelector] = useState(false);
  const [detectedEmoji, setDetectedEmoji] = useState('');

  // Calculate columns based on screen size and platform
  // For Android phones use 6 columns, for web use 8-10 based on screen size
  const numColumns =
    Platform.OS === 'web'
      ? isTablet()
        ? 10
        : 8
      : isTablet()
      ? 10
      : Platform.OS === 'android'
      ? 6
      : 5;

  // Initialize categories with custom images
  useEffect(() => {
    if (showCustomImages) {
      // Add Custom category dynamically
      if (!EMOJI_CATEGORIES.Custom) {
        EMOJI_CATEGORIES.Custom = CUSTOM_IMAGES;
      }
      setCategoryKeys(Object.keys(EMOJI_CATEGORIES));
      // Prefer Lifestyle category if available, otherwise Custom
      setSelectedCategory('Lifestyle');
    } else {
      // Remove Custom category if it exists
      if (EMOJI_CATEGORIES.Custom) {
        delete EMOJI_CATEGORIES.Custom;
      }
      setCategoryKeys(Object.keys(EMOJI_CATEGORIES));
      setSelectedCategory('Lifestyle');
    }
  }, [showCustomImages]);

  // Filter items based on search
  useEffect(() => {
    if (searchQuery) {
      const { filteredItems: searchResults, detectedEmoji: searchDetectedEmoji } =
        performEmojiSearch(searchQuery, EMOJI_CATEGORIES, EMOJI_SEARCH_INDEX);
      setFilteredItems(searchResults);
      setDetectedEmoji(searchDetectedEmoji);
    } else {
      // No search, show selected category
      setDetectedEmoji('');
      const items = EMOJI_CATEGORIES[selectedCategory] || [];
      setFilteredItems(
        items.map(item =>
          typeof item === 'string'
            ? { type: 'emoji', icon: item, category: selectedCategory }
            : { type: 'image', ...item, category: selectedCategory },
        ),
      );
    }
  }, [searchQuery, selectedCategory]);

  const handleSelect = item => {
    if (item.type === 'emoji') {
      onSelect(item.icon);
    } else {
      // For custom images, we'll use a special format
      onSelect(`image:${item.src}`);
    }
    if (mode === 'modal') {
      onClose();
    }
    setSearchQuery('');
  };


  const content = (
    <View
      style={[styles.container, mode === 'inline' && styles.inlineContainer]}
    >
      {/* Header */}
      {mode === 'modal' && (
        <View style={styles.header}>
          <Text style={styles.title}>Choose an emoji</Text>
          <TouchableOpacity onPress={onClose}>
            <Icon name="close" size={24} color="#666" />
          </TouchableOpacity>
        </View>
      )}

      {/* Search Component */}
      <EmojiSearch
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        onClearSearch={() => setSearchQuery('')}
        detectedEmoji={detectedEmoji}
        onSelectDetectedEmoji={() => handleSelect({ type: 'emoji', icon: detectedEmoji })}
        theme={theme}
      />

      {/* Category Tabs */}
      {!searchQuery && (
        <View style={styles.categoryContainer}>
          <ScrollView horizontal showsHorizontalScrollIndicator={false}>
            {categoryKeys.map(category => (
              <TouchableOpacity
                key={category}
                style={[
                  styles.categoryTab,
                  selectedCategory === category && styles.selectedCategoryTab,
                ]}
                onPress={() => setSelectedCategory(category)}
              >
                <Text
                  style={[
                    styles.categoryText,
                    selectedCategory === category &&
                      styles.selectedCategoryText,
                  ]}
                >
                  {category}
                </Text>
              </TouchableOpacity>
            ))}
          </ScrollView>
        </View>
      )}

      {/* Skin Tone Selector */}
      {selectedCategory === 'People' && !searchQuery && (
        <View style={styles.skinToneContainer}>
          <View style={styles.skinToneOptions}>
            <TouchableOpacity
              style={[
                styles.skinToneOption,
                !selectedSkinTone && styles.selectedSkinTone,
              ]}
              onPress={() => setSelectedSkinTone(null)}
            >
              <Text style={styles.skinToneEmoji}>👋</Text>
            </TouchableOpacity>
            {Object.entries(SKIN_TONE_MODIFIERS)
              .filter(([key]) => key !== 'none')
              .map(([key, modifier]) => (
                <TouchableOpacity
                  key={key}
                  style={[
                    styles.skinToneOption,
                    selectedSkinTone === modifier && styles.selectedSkinTone,
                  ]}
                  onPress={() => setSelectedSkinTone(modifier)}
                >
                  <Text style={styles.skinToneEmoji}>
                    {applySkinTone('👋', modifier)}
                  </Text>
                </TouchableOpacity>
              ))}
          </View>
        </View>
      )}


      {/* Search Results Grid */}
      <SearchResults
        filteredItems={filteredItems}
        numColumns={numColumns}
        selectedCategory={selectedCategory}
        selectedSkinTone={selectedSkinTone}
        selectedEmoji={selectedEmoji}
        onSelect={handleSelect}
        isSearching={!!searchQuery}
      />
    </View>
  );

  if (mode === 'inline') {
    return content;
  }

  return (
    <Modal
      visible={visible}
      animationType="slide"
      transparent
      onRequestClose={onClose}
    >
      <TouchableOpacity
        style={styles.modalOverlay}
        activeOpacity={1}
        onPress={onClose}
      >
        <TouchableOpacity
          activeOpacity={1}
          style={styles.modalContent}
          onPress={e => e.stopPropagation()}
        >
          {content}
        </TouchableOpacity>
      </TouchableOpacity>
    </Modal>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    borderRadius: RADIUS.xl,
    overflow: 'hidden',
    flex: 1,
  },
  inlineContainer: {
    borderRadius: RADIUS.lg,
    backgroundColor: '#f5f5f5',
    height: Platform.OS === 'web' ? 400 : 300,
    maxHeight: Platform.OS === 'web' ? 400 : 300,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    height:
      Platform.OS === 'web' ? '70%' : Platform.OS === 'android' ? '75%' : '80%',
    maxHeight:
      Platform.OS === 'web' ? 600 : Platform.OS === 'android' ? '75%' : '80%',
    maxWidth: isTablet() ? 700 : '100%',
    alignSelf: 'center',
    width: '100%',
    ...SHADOWS.level3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.lg,
    paddingHorizontal: isTablet() ? SPACING.xl : SPACING.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray[200],
  },
  title: {
    fontSize: isTablet() ? TYPOGRAPHY.sizes.xl : TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.bold,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    color: COLORS.gray[900],
  },
  categoryContainer: {
    paddingHorizontal: isTablet() ? SPACING.xl : SPACING.md,
    marginBottom: SPACING.sm,
    height: isTablet() ? 44 : 36,
  },
  categoryTab: {
    paddingHorizontal: isTablet() ? SPACING.lg : SPACING.md,
    paddingVertical: SPACING.xs,
    marginRight: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.gray[100],
    height: isTablet() ? 40 : 32,
    justifyContent: 'center',
  },
  selectedCategoryTab: {
    backgroundColor: '#667eea',
  },
  categoryText: {
    fontSize: isTablet() ? TYPOGRAPHY.sizes.md : TYPOGRAPHY.sizes.sm,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    color: COLORS.gray[700],
  },
  selectedCategoryText: {
    color: 'white',
    fontWeight: TYPOGRAPHY.weights.bold,
  },
  skinToneContainer: {
    paddingVertical: SPACING.sm,
    paddingHorizontal: isTablet() ? SPACING.xl : SPACING.md,
  },
  skinToneOptions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  skinToneOption: {
    width: isTablet() ? 44 : 36,
    height: isTablet() ? 44 : 36,
    borderRadius: RADIUS.md,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.gray[100],
  },
  selectedSkinTone: {
    backgroundColor: '#667eea',
  },
  skinToneEmoji: {
    fontSize: isTablet() ? 26 : 22,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
});

export default EmojiPicker;
