#!/bin/bash

# Generate Release Notes with Test Results
# This script creates release notes that include mandatory test results

set -e

echo "🚀 Generating Release Notes for StackMap"
echo "========================================"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get current date and version
CURRENT_DATE=$(date +"%Y-%m-%d")
CURRENT_TIME=$(date +"%H:%M:%S %Z")

# Get git information
CURRENT_BRANCH=$(git branch --show-current)
LAST_COMMIT=$(git log -1 --pretty=format:"%h - %s (%an)")
COMMIT_COUNT=$(git rev-list --count HEAD)

# Create release notes directory if it doesn't exist
mkdir -p releases

# Define release notes file
RELEASE_FILE="releases/release-notes-${CURRENT_DATE}.md"

# Function to run tests and capture results
run_tests() {
    echo -e "${YELLOW}Running UAT tests...${NC}"
    
    # Create test results directory
    mkdir -p test-results
    
    # Run tests and capture output
    if npm test > test-results/full-output.txt 2>&1; then
        TEST_STATUS="PASSED"
        TEST_COLOR=$GREEN
    else
        TEST_STATUS="FAILED"
        TEST_COLOR=$RED
    fi
    
    # Extract summary from test output
    grep -E "(Total Tests:|Passed:|Failed:|Success Rate:)" test-results/full-output.txt > test-results/summary.txt || echo "No test summary found" > test-results/summary.txt
    
    echo -e "${TEST_COLOR}Test Status: ${TEST_STATUS}${NC}"
}

# Function to check for required files
check_requirements() {
    echo -e "${YELLOW}Checking requirements...${NC}"
    
    MISSING_FILES=()
    
    # Check for critical files
    [ ! -f "package.json" ] && MISSING_FILES+=("package.json")
    [ ! -f "index.html" ] && MISSING_FILES+=("index.html")
    [ ! -f "sw.js" ] && MISSING_FILES+=("sw.js")
    [ ! -f "manifest.json" ] && MISSING_FILES+=("manifest.json")
    
    if [ ${#MISSING_FILES[@]} -ne 0 ]; then
        echo -e "${RED}Error: Missing required files:${NC}"
        printf '%s\n' "${MISSING_FILES[@]}"
        exit 1
    fi
    
    echo -e "${GREEN}All required files present${NC}"
}

# Run tests
run_tests

# Check requirements
check_requirements

# Generate release notes
echo -e "${YELLOW}Generating release notes...${NC}"

cat > "$RELEASE_FILE" << EOF
# StackMap Release Notes

**Date**: ${CURRENT_DATE}  
**Time**: ${CURRENT_TIME}  
**Branch**: ${CURRENT_BRANCH}  
**Commit**: ${LAST_COMMIT}  
**Total Commits**: ${COMMIT_COUNT}

## Test Results (REQUIRED)

### Automated UAT Tests
**Status**: ${TEST_STATUS}

\`\`\`
$(cat test-results/summary.txt)
\`\`\`

### Full Test Output
<details>
<summary>Click to expand full test results</summary>

\`\`\`
$(cat test-results/full-output.txt | tail -100)
\`\`\`
</details>

## Pre-Deployment Checklist

- [ ] All UAT tests passing
- [ ] No console errors in production build
- [ ] Service worker cache version updated
- [ ] Manifest.json version updated
- [ ] All images optimized
- [ ] Security headers configured
- [ ] SSL certificate valid

## Changes in This Release

### Features
- [ ] List new features here

### Bug Fixes
- [ ] List bug fixes here

### Performance Improvements
- [ ] List performance improvements here

### Security Updates
- [ ] List security updates here

## Deployment Steps

1. **Verify Test Results Above** - Do not proceed if tests are failing
2. **Update version numbers** in:
   - \`manifest.json\`
   - \`sw.js\` (CACHE_VERSION)
   - \`package.json\`

3. **Build and minify** (if applicable):
   \`\`\`bash
   npm run build
   \`\`\`

4. **Deploy to cPanel**:
   \`\`\`bash
   ./scripts/deploy.sh
   \`\`\`

5. **Post-deployment verification**:
   - [ ] Site loads correctly
   - [ ] PWA installs properly
   - [ ] Import/Export working
   - [ ] No console errors

## Browser Testing

- [ ] Chrome/Edge (Desktop)
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Android)
- [ ] Safari (iOS)

## Rollback Plan

If issues are discovered post-deployment:

1. Access cPanel File Manager
2. Rename current deployment to \`public_html_backup_${CURRENT_DATE}\`
3. Rename previous backup to \`public_html\`
4. Clear CDN cache if applicable

## Notes

- Test results are MANDATORY for deployment
- Never deploy with failing tests
- Always create a backup before deploying
- Monitor error logs for 24 hours post-deployment

---

Generated by: $(whoami)  
Script Version: 1.0.0
EOF

echo -e "${GREEN}Release notes generated: ${RELEASE_FILE}${NC}"

# Check if tests passed
if [ "$TEST_STATUS" = "FAILED" ]; then
    echo -e "${RED}⚠️  WARNING: Tests are failing!${NC}"
    echo -e "${RED}Do not proceed with deployment until all tests pass.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ All checks passed. Ready for deployment.${NC}"

# Display file location
echo ""
echo "Release notes location:"
echo "  ${RELEASE_FILE}"
echo ""
echo "Next steps:"
echo "1. Review and edit the release notes"
echo "2. Fill in the changes section"
echo "3. Use these notes when deploying to cPanel"