import { StyleSheet } from 'react-native';
import { TYPOGRAPHY, SPACING, RADIUS, COLORS } from '../../../constants';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    backgroundColor: '#f0f4f8',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerIcon: {
    marginRight: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: 'white',
  },
  supportContent: {
    flex: 1,
    padding: 20,
  },
  supportHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  supportHeart: {
    fontSize: 60,
    marginBottom: 16,
  },
  supportTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#5C7E9D',
    marginBottom: 8,
  },
  supportSubtitle: {
    fontSize: 18,
    color: '#8FA5B8',
  },
  teamCaption: {
    fontSize: 16,
    color: '#5C7E9D',
    fontWeight: '500',
    marginTop: 8,
    textAlign: 'center',
  },
  photoAndImpactContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 50,
    marginTop: 20,
    marginBottom: 20,
  },
  photoContainer: {
    alignItems: 'center',
    width: 450,
    maxWidth: '100%',
  },
  teamPhoto: {
    width: '100%',
    height: 300,
    borderRadius: 15,
    objectFit: 'cover',
  },
  impactWrapper: {
    width: 450,
    maxWidth: '100%',
  },
  stackMapText: {
    fontSize: 32,
    fontWeight: '700',
    color: '#5C7E9D',
    marginBottom: 10,
  },
  supportMessageBox: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  supportMessage: {
    fontSize: 16,
    lineHeight: 24,
    color: '#4a5568',
    textAlign: 'center',
  },
  supportWaysSection: {
    marginBottom: 24,
  },
  supportSectionTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#5C7E9D',
    textAlign: 'center',
    marginBottom: 20,
  },
  supportOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
  },
  supportOptionFun: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: '100%',
    maxWidth: 400,
    minWidth: 280,
    flex: 1,
  },
  supportIconBig: {
    fontSize: 36,
    marginRight: 16,
  },
  supportOptionContent: {
    flex: 1,
  },
  supportOptionTitleFun: {
    fontSize: 18,
    fontWeight: '600',
    color: '#5C7E9D',
    marginBottom: 4,
  },
  supportOptionTextFun: {
    fontSize: 14,
    lineHeight: 20,
    color: '#4a5568',
  },
  supportContactBox: {
    backgroundColor: '#5C7E9D',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginBottom: 24,
  },
  supportContactTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: 'white',
    marginBottom: 8,
  },
  supportContactText: {
    fontSize: 16,
    color: 'white',
  },
  supportFooter: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  supportFooterText: {
    fontSize: 16,
    color: '#8FA5B8',
    textAlign: 'center',
  },
  contributionList: {
    marginTop: 8,
  },
  contributionItem: {
    fontSize: 15,
    lineHeight: 24,
    color: '#4a5568',
    textAlign: 'center',
    marginBottom: 8,
    paddingHorizontal: 20,
  },
  contributionHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2d3748',
    textAlign: 'center',
    marginBottom: 20,
  },
  impactSection: {
    marginBottom: 16,
  },
  impactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 0,
  },
  impactIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E8F4F8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  impactContent: {
    flex: 1,
  },
  impactTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 4,
  },
  impactDescription: {
    fontSize: 16,
    color: '#718096',
    lineHeight: 22,
  },
});