# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro", 
  "iPad Pro (13-inch)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("StackMapNative")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, battery at 100%
override_status_bar(true)

# Arguments to pass to the app on launch
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot