import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, RADIUS, TYPOGRAPHY, SHADOWS } from '../../../constants';

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerIcon: {
    marginRight: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: Platform.OS === 'ios' ? 'bold' : 'normal',
    color: 'white',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  modalContent: {
    padding: 20,
  },
  section: {
    marginBottom: 30,
  },
  sectionCollapsed: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 15,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  inputGroup: {
    marginBottom: SPACING.lg,
  },
  label: {
    fontSize: 14,
    color: '#000',
    marginBottom: SPACING.sm,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.gray[300],
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    fontSize: 16,
    backgroundColor: 'white',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.gray[100],
    borderRadius: RADIUS.md,
    padding: 4,
  },
  toggle: {
    flex: 1,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
  },
  toggleActive: {
    backgroundColor: COLORS.white,
    ...SHADOWS.level1,
  },
  toggleText: {
    fontSize: TYPOGRAPHY.sizes.sm,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    color: '#000',
  },
  toggleTextActive: {
    color: COLORS.gray[900],
    fontWeight: '600',
  },
  checkboxGroup: {
    marginTop: SPACING.md,
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  checkboxContainer: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SPACING.sm,
  },
  checkboxLabel: {
    marginLeft: SPACING.sm,
    fontSize: 16,
    color: '#333',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  autoUpdateHint: {
    fontSize: 14,
    color: '#000',
    marginTop: SPACING.xs,
    marginLeft: 32,
    fontStyle: 'italic',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  tokenPreview: {
    backgroundColor: COLORS.gray[100],
    borderRadius: RADIUS.md,
    padding: SPACING.lg,
    alignItems: 'center',
    marginVertical: SPACING.lg,
  },
  tokenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  tokenLabel: {
    fontSize: 14,
    color: '#000',
    marginLeft: SPACING.xs,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  tokenText: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.gray[700],
    letterSpacing: 1,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    maxWidth: '80%',
  },
  tokenHint: {
    fontSize: 14,
    color: '#000',
    marginTop: SPACING.sm,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: RADIUS.md,
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
    ...SHADOWS.level1,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.lg,
    ...SHADOWS.level1,
  },
  createButtonDisabled: {
    opacity: 0.6,
  },
  createButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: SPACING.sm,
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  shareSection: {
    backgroundColor: COLORS.gray[50],
    borderRadius: RADIUS.md,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
  },
  successHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.lg,
    gap: SPACING.sm,
  },
  newShareLink: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.md,
    backgroundColor: 'white',
    gap: SPACING.xs,
    ...SHADOWS.level1,
  },
  newShareLinkText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  shareUrl: {
    backgroundColor: 'white',
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.gray[200],
  },
  shareUrlText: {
    fontSize: 14,
    color: COLORS.info,
    textDecorationLine: 'underline',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  qrContainer: {
    alignItems: 'center',
    padding: SPACING.lg,
    backgroundColor: 'white',
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
  },
  copyButton: {
    backgroundColor: COLORS.info,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.sm,
  },
  copyButtonText: {
    color: 'white',
    fontSize: 16,
    marginLeft: SPACING.sm,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  deleteButton: {
    backgroundColor: '#e53e3e',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: RADIUS.md,
  },
  deleteButtonText: {
    color: 'white',
    fontSize: 16,
    marginLeft: SPACING.sm,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  metaInfo: {
    backgroundColor: COLORS.gray[50],
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginTop: SPACING.md,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SPACING.xs,
  },
  metaLabel: {
    fontSize: 14,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  metaValue: {
    fontSize: 14,
    color: COLORS.gray[900],
    fontWeight: '500',
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  activeSharesSection: {
    marginTop: SPACING.lg,
  },
  activeSharesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  activeSharesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  activeSharesList: {
    marginTop: SPACING.sm,
  },
  activeShareItem: {
    backgroundColor: 'white',
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.gray[200],
    ...SHADOWS.level1,
  },
  idleShareItem: {
    borderColor: COLORS.warning,
    backgroundColor: '#fffaf0',
  },
  activeShareInfo: {
    flex: 1,
  },
  activeShareRecipient: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  activeShareMeta: {
    fontSize: 14,
    color: '#000',
    marginTop: 2,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  activeShareActions: {
    flexDirection: 'row',
    marginTop: SPACING.sm,
    gap: SPACING.sm,
  },
  viewShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    backgroundColor: COLORS.gray[100],
    borderRadius: RADIUS.sm,
  },
  viewShareButtonText: {
    fontSize: 12,
    color: COLORS.gray[700],
    marginLeft: 4,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  extendShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    backgroundColor: '#f0f9ff',
    borderRadius: RADIUS.sm,
  },
  extendShareButtonText: {
    fontSize: 12,
    marginLeft: 4,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  deleteShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    backgroundColor: '#fee',
    borderRadius: RADIUS.sm,
  },
  deleteShareButtonText: {
    fontSize: 12,
    color: '#e53e3e',
    marginLeft: 4,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  extendControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  miniToggleContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.gray[100],
    borderRadius: RADIUS.sm,
    padding: 2,
  },
  miniToggle: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  miniToggleActive: {
    backgroundColor: COLORS.white,
    ...SHADOWS.level1,
  },
  miniToggleText: {
    fontSize: 11,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    color: COLORS.gray[600],
  },
  miniToggleTextActive: {
    color: COLORS.gray[900],
    fontWeight: '600',
  },
  extendButtons: {
    flexDirection: 'row',
    gap: 4,
  },
  extendConfirmButton: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  extendCancelButton: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.gray[200],
    alignItems: 'center',
    justifyContent: 'center',
  },
  autoUpdateBadge: {
    backgroundColor: '#e6fffa',
    paddingHorizontal: SPACING.xs,
    paddingVertical: 2,
    borderRadius: RADIUS.round,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  autoUpdateText: {
    color: COLORS.success,
    fontSize: 10,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  idleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  idleBadgeText: {
    color: COLORS.warning,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  toggleButton: {
    padding: SPACING.xs,
  },
});

export default styles;