import { StyleSheet, Platform } from 'react-native';
import { TYPOGRAPHY, SPACING, RADIUS, COLORS, SHADOWS } from '../../../constants';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: 'white',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 16,
    marginTop: 24,
  },
  usersList: {
    backgroundColor: 'white',
    borderRadius: RADIUS.medium,
    overflow: 'hidden',
    ...SHADOWS.medium,
  },
  userItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  userItemActive: {
    backgroundColor: '#f0f9ff',
  },
  userItemEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  userItemName: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  userItemNameActive: {
    fontWeight: '600',
  },
  editUserButton: {
    padding: 8,
    marginLeft: 8,
  },
  deleteUserButton: {
    padding: 8,
    marginLeft: 4,
  },
  addUserButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#f8f9fa',
  },
  addUserText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '500',
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    borderRadius: RADIUS.medium,
    padding: 4,
  },
  toggle: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: RADIUS.small,
  },
  toggleActive: {
    backgroundColor: 'white',
    ...SHADOWS.small,
  },
  toggleText: {
    fontSize: 14,
    color: '#666',
  },
  toggleTextActive: {
    fontWeight: '600',
    color: '#333',
  },
  pinSection: {
    backgroundColor: 'white',
    borderRadius: RADIUS.medium,
    padding: 20,
    ...SHADOWS.medium,
  },
  pinStatus: {
    fontSize: 16,
    color: '#666',
    marginBottom: 16,
  },
  pinButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  pinButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: RADIUS.small,
    alignItems: 'center',
  },
  pinButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: RADIUS.medium,
    gap: 8,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  settingsSection: {
    backgroundColor: 'white',
    borderRadius: RADIUS.medium,
    padding: 20,
    ...SHADOWS.medium,
  },
  syncStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  syncStatusText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  syncDescription: {
    fontSize: 14,
    color: '#666',
    marginBottom: 16,
    lineHeight: 20,
  },
  recoveryPhraseContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: RADIUS.small,
    padding: 16,
    marginBottom: 16,
  },
  recoveryPhraseLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  recoveryPhrase: {
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: '#333',
    marginBottom: 12,
    lineHeight: 24,
  },
  recoveryPhraseWarning: {
    fontSize: 13,
    color: '#e67e22',
    lineHeight: 18,
  },
  recoveryInputContainer: {
    marginBottom: 16,
  },
  recoveryInputLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  recoveryInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: RADIUS.small,
    padding: 12,
    fontSize: 16,
    marginBottom: 8,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  recoveryInputButtons: {
    flexDirection: 'row',
    marginTop: 8,
  },
  errorText: {
    color: COLORS.error,
    fontSize: 13,
    marginBottom: 8,
  },
  dangerZone: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#ffcdd2',
  },
  dangerZoneText: {
    fontSize: 12,
    color: '#666',
    marginTop: 12,
    lineHeight: 18,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  qrCodeContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginVertical: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  qrCodeHint: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 15,
  },
  qrScanHint: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 12,
    fontStyle: 'italic',
  },
});