import { StyleSheet, Platform } from 'react-native';
import { COLORS, TYPOGRAPHY, SPACING, RADIUS, SHADOWS } from '../../../constants';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerIcon: {
    marginRight: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: Platform.OS === 'ios' ? 'bold' : 'normal',
    color: 'white',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  modalContent: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: Platform.OS === 'ios' ? 0 : SPACING.xs,
    flexGrow: Platform.OS === 'ios' ? 0 : 1,
  },
  
  // Top Action Container
  topActionContainer: {
    backgroundColor: 'white',
    paddingVertical: Platform.OS === 'ios' ? 8 : SPACING.xl,
    paddingHorizontal: Platform.OS === 'ios' ? 12 : SPACING.lg,
    margin: Platform.OS === 'ios' ? 6 : SPACING.md,
    marginBottom: Platform.OS === 'ios' ? 2 : SPACING.xs,
    alignItems: 'center',
    borderRadius: Platform.OS === 'ios' ? RADIUS.md : RADIUS.lg,
    borderWidth: Platform.OS === 'ios' ? 0 : 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'ios' ? 1 : 2 },
    shadowOpacity: Platform.OS === 'ios' ? 0.02 : 0.04,
    shadowRadius: Platform.OS === 'ios' ? 2 : 6,
    elevation: Platform.OS === 'ios' ? 1 : 2,
  },
  explanationText: {
    fontSize: Platform.OS === 'ios' ? 15 : 16,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    textAlign: 'center',
    lineHeight: Platform.OS === 'ios' ? 20 : 22,
    marginBottom: Platform.OS === 'ios' ? 4 : SPACING.xs,
  },
  explanationSubtext: {
    fontSize: Platform.OS === 'ios' ? 13 : 14,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    textAlign: 'center',
    marginBottom: Platform.OS === 'ios' ? SPACING.xs : SPACING.sm,
  },
  
  // Sections
  section: {
    backgroundColor: 'white',
    marginTop: Platform.OS === 'ios' ? 2 : SPACING.md,
    marginBottom: Platform.OS === 'ios' ? 2 : 0,
    marginHorizontal: Platform.OS === 'ios' ? 6 : SPACING.md,
    paddingTop: Platform.OS === 'ios' ? 6 : SPACING.lg,
    paddingBottom: Platform.OS === 'ios' ? 4 : SPACING.lg,
    paddingHorizontal: Platform.OS === 'ios' ? 8 : SPACING.lg,
    borderRadius: Platform.OS === 'ios' ? RADIUS.md : RADIUS.lg,
    borderWidth: Platform.OS === 'ios' ? 0 : 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'ios' ? 1 : 2 },
    shadowOpacity: Platform.OS === 'ios' ? 0.02 : 0.04,
    shadowRadius: Platform.OS === 'ios' ? 2 : 6,
    elevation: Platform.OS === 'ios' ? 1 : 2,
    minHeight: Platform.OS === 'ios' ? undefined : 'auto',
    flex: Platform.OS === 'ios' ? 0 : undefined,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Platform.OS === 'ios' ? 4 : SPACING.sm,
  },
  sectionIconContainer: {
    width: Platform.OS === 'ios' ? 32 : 40,
    height: Platform.OS === 'ios' ? 32 : 40,
    borderRadius: Platform.OS === 'ios' ? 16 : 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Platform.OS === 'ios' ? 8 : SPACING.md,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  sectionTitle: {
    fontSize: Platform.OS === 'ios' ? 17 : 18,
    fontWeight: Platform.OS === 'ios' ? '600' : 'normal',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    color: '#000',
  },
  sectionCount: {
    fontSize: 16,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    marginLeft: SPACING.xs,
  },
  sectionDescription: {
    fontSize: Platform.OS === 'ios' ? 11 : 13,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    marginBottom: Platform.OS === 'ios' ? 2 : SPACING.sm,
    opacity: 0.7,
    lineHeight: Platform.OS === 'ios' ? 14 : 18,
  },
  
  // Activities Container
  activitiesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: Platform.OS === 'ios' ? 0 : SPACING.sm,
    marginLeft: Platform.OS === 'ios' ? -3 : -SPACING.xs,
    marginRight: Platform.OS === 'ios' ? -3 : 0,
    minHeight: Platform.OS === 'ios' ? undefined : 'auto',
    flex: Platform.OS === 'ios' ? 0 : undefined,
    flexGrow: Platform.OS === 'ios' ? 0 : undefined,
    flexShrink: Platform.OS === 'ios' ? 1 : undefined,
  },
  
  // Activity Card
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Platform.OS === 'ios' ? '#f5f5f5' : 'white',
    borderRadius: Platform.OS === 'ios' ? 6 : RADIUS.lg,
    paddingVertical: Platform.OS === 'ios' ? 6 : 12,
    paddingHorizontal: Platform.OS === 'ios' ? 10 : 16,
    marginLeft: Platform.OS === 'ios' ? 3 : SPACING.xs,
    marginRight: Platform.OS === 'ios' ? 3 : 0,
    marginBottom: Platform.OS === 'ios' ? 3 : SPACING.sm,
    borderWidth: 0,
    borderColor: 'rgba(0,0,0,0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  actionIcon: {
    marginLeft: 'auto',
    marginRight: SPACING.xs,
  },
  activityEmoji: {
    fontSize: Platform.OS === 'ios' ? 16 : 20,
    marginRight: Platform.OS === 'ios' ? 4 : SPACING.xs,
  },
  activityText: {
    fontSize: Platform.OS === 'ios' ? 12 : 14,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    flex: 1,
    lineHeight: Platform.OS === 'ios' ? 16 : 20,
  },
  emptyText: {
    fontSize: 14,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontStyle: 'italic',
  },
  
  // Summary
  summaryContainer: {
    backgroundColor: 'white',
    paddingVertical: Platform.OS === 'ios' ? 6 : SPACING.lg,
    paddingHorizontal: Platform.OS === 'ios' ? 10 : SPACING.lg,
    marginTop: Platform.OS === 'ios' ? 2 : SPACING.md,
    marginHorizontal: Platform.OS === 'ios' ? 6 : SPACING.md,
    marginBottom: Platform.OS === 'ios' ? 4 : SPACING.md,
    borderRadius: Platform.OS === 'ios' ? RADIUS.md : RADIUS.lg,
    borderWidth: Platform.OS === 'ios' ? 0 : 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'ios' ? 1 : 2 },
    shadowOpacity: Platform.OS === 'ios' ? 0.02 : 0.04,
    shadowRadius: Platform.OS === 'ios' ? 2 : 6,
    elevation: Platform.OS === 'ios' ? 1 : 2,
  },
  summaryTitle: {
    fontSize: Platform.OS === 'ios' ? 14 : 16,
    fontWeight: Platform.OS === 'ios' ? '600' : 'normal',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    color: '#000',
    marginBottom: Platform.OS === 'ios' ? 2 : SPACING.sm,
  },
  summaryText: {
    fontSize: Platform.OS === 'ios' ? 12 : 14,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    lineHeight: Platform.OS === 'ios' ? 16 : 22,
    marginBottom: Platform.OS === 'ios' ? 1 : SPACING.xs,
  },
  
  // Actions
  actionContainer: {
    backgroundColor: 'white',
    padding: SPACING.lg,
    paddingTop: SPACING.md,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Platform.OS === 'ios' ? 10 : 16,
    paddingHorizontal: Platform.OS === 'ios' ? 24 : 40,
    borderRadius: Platform.OS === 'ios' ? RADIUS.lg : RADIUS.xl,
    marginTop: Platform.OS === 'ios' ? 8 : SPACING.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'ios' ? 2 : 4 },
    shadowOpacity: Platform.OS === 'ios' ? 0.1 : 0.15,
    shadowRadius: Platform.OS === 'ios' ? 4 : 8,
    elevation: Platform.OS === 'ios' ? 2 : 4,
  },
  buttonIcon: {
    marginRight: SPACING.xs,
  },
  buttonText: {
    color: 'white',
    fontSize: Platform.OS === 'ios' ? 15 : 17,
    fontWeight: Platform.OS === 'ios' ? '600' : 'normal',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    letterSpacing: Platform.OS === 'ios' ? 0.3 : 0.5,
  },
  cancelButton: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  cancelButtonText: {
    color: '#000',
    fontSize: 16,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
});