import { StyleSheet, Platform } from 'react-native';
import { COLORS, TYPOGRAPHY, SPACING, RADIUS, SHADOWS } from '../../../constants';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerIcon: {
    marginRight: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: Platform.OS === 'ios' ? 'bold' : 'normal',
    color: 'white',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  modalContent: {
    padding: 20,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  sectionDescription: {
    fontSize: 14,
    color: '#000',
    lineHeight: 20,
    marginBottom: SPACING.md,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  statusContainer: {
    backgroundColor: 'white',
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    ...SHADOWS.level1,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: SPACING.xs,
  },
  statusLabel: {
    fontSize: 14,
    color: '#000',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  statusValue: {
    fontSize: 14,
    color: COLORS.gray[900],
    fontFamily: TYPOGRAPHY.fontFamily.medium,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: RADIUS.md,
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
    ...SHADOWS.level1,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  closeButton: {
    padding: SPACING.xs,
  },
  disabledText: {
    fontSize: 14,
    color: COLORS.gray[500],
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  connectedBadge: {
    backgroundColor: '#e6fffa',
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: RADIUS.round,
  },
  connectedText: {
    color: COLORS.success,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily.bold,
  },
  recoveryPhraseContainer: {
    marginTop: SPACING.md,
  },
  recoveryPhrase: {
    backgroundColor: COLORS.gray[100],
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.sm,
  },
  recoveryPhraseText: {
    fontSize: 14,
    fontFamily: 'monospace',
    color: COLORS.gray[900],
    textAlign: 'center',
    lineHeight: 20,
  },
  infoText: {
    fontSize: 12,
    color: '#000',
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  errorText: {
    color: COLORS.error,
    fontSize: 14,
    marginTop: SPACING.sm,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.gray[300],
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    fontSize: 16,
    marginBottom: SPACING.md,
    backgroundColor: 'white',
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  warningContainer: {
    backgroundColor: '#fffff0',
    borderWidth: 1,
    borderColor: COLORS.warning,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginTop: SPACING.md,
  },
  warningText: {
    color: COLORS.warning,
    fontSize: 14,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
  },
  qrContainer: {
    alignItems: 'center',
    padding: SPACING.lg,
    backgroundColor: 'white',
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
    ...SHADOWS.level1,
  },
});